# Generated by Django 5.2.1 on 2025-05-07 20:30

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('official_name', models.CharField(max_length=200)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(max_length=3, unique=True)),
                ('ccn3', models.CharField(blank=True, max_length=3, null=True)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('independent', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('un_member', models.BooleanField(default=False)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('area', models.FloatField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('tlds', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('start_of_week', models.CharField(default='monday', max_length=10)),
                ('gini', models.JSONField(blank=True, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('car_signs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, null=True, size=None)),
                ('car_side', models.CharField(blank=True, max_length=5, null=True)),
                ('timezones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, null=True, size=None)),
                ('continents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('google_maps_url', models.URLField(blank=True, max_length=255, null=True)),
                ('openstreetmap_url', models.URLField(blank=True, max_length=255, null=True)),
                ('flag_png_url', models.URLField(blank=True, max_length=255, null=True)),
                ('flag_svg_url', models.URLField(blank=True, max_length=255, null=True)),
                ('flag_alt', models.TextField(blank=True, null=True)),
                ('coat_of_arms_png_url', models.URLField(blank=True, max_length=255, null=True)),
                ('coat_of_arms_svg_url', models.URLField(blank=True, max_length=255, null=True)),
                ('postal_code_format', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code_regex', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CapitalCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitals', to='countryapp.country')),
            ],
            options={
                'verbose_name_plural': 'Capital Cities',
            },
        ),
        migrations.CreateModel(
            name='AlternativeSpelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_spellings', to='countryapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalDialingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=5)),
                ('suffixes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, null=True, size=None)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idd', to='countryapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='BorderCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borders_from', to='countryapp.country')),
                ('to_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borders_to', to='countryapp.country')),
            ],
            options={
                'verbose_name_plural': 'Border Countries',
                'unique_together': {('from_country', 'to_country')},
            },
        ),
        migrations.CreateModel(
            name='CountryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('official_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='countryapp.country')),
            ],
            options={
                'unique_together': {('country', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('official_name', models.CharField(max_length=200)),
                ('common_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='countryapp.country')),
            ],
            options={
                'unique_together': {('country', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='CountryCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='countryapp.country')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countryapp.currency')),
            ],
            options={
                'unique_together': {('country', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='Demonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3)),
                ('male', models.CharField(max_length=100)),
                ('female', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demonyms', to='countryapp.country')),
            ],
            options={
                'unique_together': {('country', 'language')},
            },
        ),
        migrations.CreateModel(
            name='CountryLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='countryapp.country')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='countryapp.language')),
            ],
            options={
                'unique_together': {('country', 'language')},
            },
        ),
    ]
