# Generated by Django 5.2.1 on 2025-05-08 03:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internationaldialingcode',
            name='root',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='internationaldialingcode',
            name='suffixes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
