# Generated by Django 5.2.1 on 2025-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryapp', '0002_alter_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='postal_code_format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
