# Generated by Django 5.2.1 on 2025-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countryapp', '0003_alter_country_postal_code_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='postal_code_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
